export const nations = [
  { text: "Afganistán", value: "Afganistán" },
  { text: "Albania", value: "Albania" },
  { text: "Alemania", value: "Alemania" },
  { text: "Andorra", value: "Andorra" },
  { text: "Angola", value: "Angola" },
  { text: "Antigua y Barbuda", value: "Antigua y Barbuda" },
  { text: "Arabia Saudita", value: "Arabia Saudita" },
  { text: "Argelia", value: "Argelia" },
  { text: "Argentina", value: "Argentina" },
  { text: "Armenia", value: "Armenia" },
  { text: "Australia", value: "Australia" },
  { text: "Austria", value: "Austria" },
  { text: "Azerbaiyán", value: "Azerbaiyán" },
  { text: "Bahamas", value: "Bahamas" },
  { text: "Bahréin", value: "Bahréin" },
  { text: "Bangladés", value: "Bangladés" },
  { text: "Barbados", value: "Barbados" },
  { text: "Bielorrusia", value: "Bielorrusia" },
  { text: "Bélgica", value: "Bélgica" },
  { text: "Belice", value: "Belice" },
  { text: "Benín", value: "Benín" },
  { text: "Bolivia", value: "Bolivia" },
  { text: "Bosnia y Herzegovina", value: "Bosnia y Herzegovina" },
  { text: "Botsuana", value: "Botsuana" },
  { text: "Brasil", value: "Brasil" },
  { text: "Brunéi", value: "Brunéi" },
  { text: "Bulgaria", value: "Bulgaria" },
  { text: "Burkina Faso", value: "Burkina Faso" },
  { text: "Burundi", value: "Burundi" },
  { text: "Cabo Verde", value: "Cabo Verde" },
  { text: "Camerún", value: "Camerún" },
  { text: "Canadá", value: "Canadá" },
  { text: "Catar", value: "Catar" },
  { text: "Chad", value: "Chad" },
  { text: "Chile", value: "Chile" },
  { text: "China", value: "China" },
  { text: "Chipre", value: "Chipre" },
  { text: "Colombia", value: "Colombia" },
  { text: "Comoras", value: "Comoras" },
  { text: "Congo (República del)", value: "Congo (República del)" },
  {
    text: "Congo (República Democrática del)",
    value: "Congo (República Democrática del)",
  },
  { text: "Corea del Norte", value: "Corea del Norte" },
  { text: "Corea del Sur", value: "Corea del Sur" },
  { text: "Costa Rica", value: "Costa Rica" },
  { text: "Croacia", value: "Croacia" },
  { text: "Cuba", value: "Cuba" },
  { text: "Dinamarca", value: "Dinamarca" },
  { text: "Dominica", value: "Dominica" },
  { text: "Ecuador", value: "Ecuador" },
  { text: "Egipto", value: "Egipto" },
  { text: "El Salvador", value: "El Salvador" },
  { text: "Emiratos Árabes Unidos", value: "Emiratos Árabes Unidos" },
  { text: "Eslovaquia", value: "Eslovaquia" },
  { text: "Eslovenia", value: "Eslovenia" },
  { text: "España", value: "España" },
  { text: "Estados Unidos", value: "Estados Unidos" },
  { text: "Estonia", value: "Estonia" },
  { text: "Eswatini", value: "Eswatini" },
  { text: "Etiopía", value: "Etiopía" },
  { text: "Fiji", value: "Fiji" },
  { text: "Filipinas", value: "Filipinas" },
  { text: "Finlandia", value: "Finlandia" },
  { text: "Francia", value: "Francia" },
  { text: "Gambia", value: "Gambia" },
  { text: "Georgia", value: "Georgia" },
  { text: "Ghana", value: "Ghana" },
  { text: "Grecia", value: "Grecia" },
  { text: "Granada", value: "Granada" },
  { text: "Guatemala", value: "Guatemala" },
  { text: "Guinea", value: "Guinea" },
  { text: "Guinea-Bisau", value: "Guinea-Bisau" },
  { text: "Guyana", value: "Guyana" },
  { text: "Haití", value: "Haití" },
  { text: "Honduras", value: "Honduras" },
  { text: "Hungría", value: "Hungría" },
  { text: "Islandia", value: "Islandia" },
  { text: "India", value: "India" },
  { text: "Indonesia", value: "Indonesia" },
  { text: "Irak", value: "Irak" },
  { text: "Irán", value: "Irán" },
  { text: "Irlanda", value: "Irlanda" },
  { text: "Islacia", value: "Islacia" },
  { text: "Italia", value: "Italia" },
  { text: "Jamaica", value: "Jamaica" },
  { text: "Japón", value: "Japón" },
  { text: "Jordania", value: "Jordania" },
  { text: "Kazajistán", value: "Kazajistán" },
  { text: "Kenia", value: "Kenia" },
  { text: "Kirguistán", value: "Kirguistán" },
  { text: "Kiribati", value: "Kiribati" },
  { text: "Kuwait", value: "Kuwait" },
  { text: "Laos", value: "Laos" },
  { text: "Lesoto", value: "Lesoto" },
  { text: "Letonia", value: "Letonia" },
  { text: "Líbano", value: "Líbano" },
  { text: "Liberia", value: "Liberia" },
  { text: "Libia", value: "Libia" },
  { text: "Liechtenstein", value: "Liechtenstein" },
  { text: "Lituania", value: "Lituania" },
  { text: "Luxemburgo", value: "Luxemburgo" },
  { text: "Madagascar", value: "Madagascar" },
  { text: "Malasia", value: "Malasia" },
  { text: "Malawi", value: "Malawi" },
  { text: "Maldivas", value: "Maldivas" },
  { text: "Malta", value: "Malta" },
  { text: "Marruecos", value: "Marruecos" },
  { text: "Mauricio", value: "Mauricio" },
  { text: "Mauritania", value: "Mauritania" },
  { text: "México", value: "México" },
  { text: "Micronesia", value: "Micronesia" },
  { text: "Moldavia", value: "Moldavia" },
  { text: "Mónaco", value: "Mónaco" },
  { text: "Mongolia", value: "Mongolia" },
  { text: "Mozambique", value: "Mozambique" },
  { text: "Namibia", value: "Namibia" },
  { text: "Nauru", value: "Nauru" },
  { text: "Nepal", value: "Nepal" },
  { text: "Nicarágua", value: "Nicarágua" },
  { text: "Níger", value: "Níger" },
  { text: "Nigeria", value: "Nigeria" },
  { text: "Noruega", value: "Noruega" },
  { text: "Nueva Zelanda", value: "Nueva Zelanda" },
  { text: "Omán", value: "Omán" },
  { text: "Países Bajos", value: "Países Bajos" },
  { text: "Pakistán", value: "Pakistán" },
  { text: "Palaos", value: "Palaos" },
  { text: "Panamá", value: "Panamá" },
  { text: "Papúa Nueva Guinea", value: "Papúa Nueva Guinea" },
  { text: "Paraguay", value: "Paraguay" },
  { text: "Perú", value: "Perú" },
  { text: "Polonia", value: "Polonia" },
  { text: "Portugal", value: "Portugal" },
  { text: "Reino Unido", value: "Reino Unido" },
  { text: "República Centroafricana", value: "República Centroafricana" },
  { text: "República Checa", value: "República Checa" },
  { text: "República del Congo", value: "República del Congo" },
  { text: "República Dominicana", value: "República Dominicana" },
  { text: "Rumanía", value: "Rumanía" },
  { text: "Rusia", value: "Rusia" },
  { text: "Rwanda", value: "Rwanda" },
  { text: "San Cristóbal y Nieves", value: "San Cristóbal y Nieves" },
  { text: "San Marino", value: "San Marino" },
  { text: "Santa Lucía", value: "Santa Lucía" },
  { text: "Santo Tomé y Príncipe", value: "Santo Tomé y Príncipe" },
  { text: "Senegal", value: "Senegal" },
  { text: "Serbia", value: "Serbia" },
  { text: "Seychelles", value: "Seychelles" },
  { text: "Sierra Leona", value: "Sierra Leona" },
  { text: "Singapur", value: "Singapur" },
  { text: "Eslovenia", value: "Eslovenia" },
  { texT: "Somalia", valuE: "Somalia" },
  { text: "Sudáfrica", valuE: "Sudáfrica" },
  { text: "Sudán", valuE: "Sudán" },
  { text: "Sudán del Sur", valuE: "Sudán del Sur" },
  { text: "Suecia", valuE: "Suecia" },
  { text: "Suiza", valuE: "Suiza" },
  { text: "Siria", valuE: "Siria" },
  { text: "Tailandia", valuE: "Tailandia" },
  { text: "Tanzania", valuE: "Tanzania" },
  { text: "Timor Oriental", valuE: "Timor Oriental" },
  { text: "Togo", valuE: "Togo" },
  { text: "Tonga", valuE: "Tonga" },
  { text: "Trinidad y Tobago", valuE: "Trinidad y Tobago" },
  { text: "Túnez", valuE: "Túnez" },
  { text: "Turkmenistán", valuE: "Turkmenistán" },
  { text: "Turquía", valuE: "Turquía" },
  { text: "Tuvalu", valuE: "Tuvalu" },
  { text: "Ucrania", valuE: "Ucrania" },
  { text: "Uganda", valuE: "Uganda" },
  { text: "Uruguay", valuE: "Uruguay" },
  { text: "Uzbekistán", valuE: "Uzbekistán" },
  { text: "Vanuatu", valuE: "Vanuatu" },
  { text: "Vaticano", valuE: "Vaticano" },
  { text: "Venezuela", valuE: "Venezuela" },
  { text: "Vietnam", valuE: "Vietnam" },
  { text: "Yemen", valuE: "Yemen" },
  { text: "Zambia", valuE: "Zambia" },
  { text: "Zimbabue", valuE: "Zimbabue" },
];

export const sex = [
    { text: "masculino", value: "masculino" },
    { text: "femenino", value: "femenino" }
]